alpha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth_part.urls')),
    url(r'^user/', include('plants.urls')),
    url(r'^sensor/', include('sensors.urls')),

]

auth_part/urls.py
from django.conf.urls import url
from . import views

app_name='auth_part'

urlpatterns = [
    url(r'^newuser/$', views.create_profile, name='createprofile'),
    url(r'^$', views.login, name='login'),
    url(r'^logout/', views.logout_view, name='logout'), #directly logging out by importing logout in view and using it here.   
]

jidos/urls.py
from django.conf.urls import url
from .views import add_plant, viewdashboard, plantboard, last_readings

app_name = 'plants'
urlpatterns = [
    url(r'^add/$', add_plant, name='addplant'),
    url(r'^dashboard/$', viewdashboard, name='dashboard'),
    url(r'^(?P<username>[0-9A-Za-z\.@\-\ ]+)/tables', last_readings, name='last-readings'),

    url(r'^(?P<username>[0-9A-Za-z\.@\-\ ]+)/$', plantboard, name='plantboard'),

]

jidos/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.
class Plant(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = models.ForeignKey(User, on_delete=models.CASCADE)
    alias = models.CharField(max_length=20, default=None, null=True, blank=True)
    lat = models.FloatField(default=13.5115)
    lon = models.FloatField(default=80.0144)

    def __str__(self):
        if self.alias:
            return self.alias
        return str(self.id)

    def get_absolute_url(self):
        return "/user" + "/" + str(self.alias)

jidos/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from sensors.models import Sensor, SensorData, Actuator

from .models import Plant


# Create your views here.
@login_required(login_url='/')
@csrf_exempt
def add_plant(request):
    if request.method == 'POST':
        plant = Plant()
        if (not request.POST.get('alias')) or len(Plant.objects.filter(alias=request.POST.get('alias'))) != 0:
            return HttpResponseRedirect(reverse('plants:dashboard'))
        plant.alias = request.POST.get('alias')
        plant.parent = request.user
        plant.save()
        sensor1 = Sensor()
        sensor1.sensor_type = 'GPS Module'
        sensor1.parent = plant
        sensor1.save()
        actuator = Actuator()
        actuator.parent = plant
        actuator.name = request.POST.get('alias')
        actuator.state = 0
        actuator.save()

        return HttpResponseRedirect(reverse('plants:dashboard'))
    return HttpResponseRedirect(reverse('plants:dashboard'))


@login_required(login_url='/')
def viewdashboard(request):
    print(request.user)
    plants = Plant.objects.filter(parent=request.user)
    print(plants)
    return render(request, 'userdashboard.html', {'username': request.user.username, 'plants': plants})


@login_required(login_url='/')
def last_readings(request, username):
    print(username)
    plant = Plant.objects.get(alias=username, parent=request.user)
    print(plant.alias)
    sensors = plant.sensor_set.all()
    gps_values = SensorData.objects.filter(parent__sensor_type='GPS Module', parent__parent=plant)[:100]
    gps_values = list(map(lambda x: model_to_dict(x), gps_values))

    dict1 = {'gps_values': gps_values}
    return JsonResponse(dict1, safe=False)


@login_required(login_url='/')
def plantboard(request, username):
    print(username)
    plant = Plant.objects.get(alias=username, parent=request.user)
    print(plant.alias)
    sensors = plant.sensor_set.all()
    print(sensors)
    gps_sensor = sensors.filter(sensor_type='GPS Module')[0]
    sensor_data_gps = SensorData.objects.filter(parent=gps_sensor)
    act = Actuator.objects.get(parent__alias=username, name=plant.alias)
    try:
        gps = sensor_data_gps.latest('id')
    except Exception:
        gps = None

    gps_values = list(map(lambda x: x.value, list(sensor_data_gps)[-1:-11:-1]))

    context = {'plant': plant,
               'sensors': sensors,
               'location': gps,
               'gps_values': gps_values[::-1]
               }
    print(context)
    return render(request, "plant1.html", context=context)
    return HttpResponse(str(id))

jidos/templates/userdashboard.html
{% load staticfiles%}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Jido Tags</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'plants/css/main.css' %}" />
		<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
		
	</head>
	<body>

		<!-- Header -->			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48" style="background-color:inherit !important;"><img src="{% static 'plants/images/man.svg' %}" alt="" /></span>
							<h1 id="title">{{ username }}</h1>
							
						</div>

					<!-- Nav -->
						<nav id="nav">
							<!--

								Prologue's nav expects links in one of two formats:

								1. Hash link (scrolls to a different section within the page)

								   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

								2. Standard link (sends the user to another page/site)

								   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

							-->
							<ul>
								<li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Map</span></a></li>
								<li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">About Us</span></a></li>
								<li><a href="#contact" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Add Jido</span></a></li>
								<a href="{% url 'auth_part:logout' %}"><button style="margin-right: 20px;margin-top: 10px;">Logout</button></a>								
								<center><li>Your Jidos</li></center>
								<hr/>								
								{% for plant in plants %}
									{% if plant.alias %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% else %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% endif %}		
									</a>
								{% endfor %}
							</ul>
						</nav>

				</div>

			<!--	<div class="bottom">

					
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</div> -->

			</div>

		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

						<div id="map"></div>
							<script>

							function initMap() {

								var kobelco = {lat:13.552641, lng:80.016036};

								var iiit = {lat:13.555439, lng:80.027366};

								var ifmr = {lat:13.549934, lng:80.000071};

								var map = new google.maps.Map(document.getElementById('map'), {

								zoom: 15,

								center: kobelco

								});

								var jido1 = new google.maps.Marker({

								position: iiit,

								map: map

								});



								var jido2 = new google.maps.Marker({

								position: ifmr,

								map: map

								});



								var infowindow1 = new google.maps.InfoWindow({

								content: '<b>Jido 1</b>'

								});



								var infowindow2 = new google.maps.InfoWindow({

								content: '<b>Jido 2</b>'

								});



								infowindow1.open(map, jido1);

								infowindow2.open(map, jido2);



							}

							</script>
							<script async defer
							src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
							</script>

						</div>
					</section>

			

				<!-- About Us -->
					<section id="about" class="three">
						<div class="container">

							<header>
								<h2>About Us</h2>
							</header>

							<a href="#" class="image featured"><img src="http://staugustine.com/sites/default/files/styles/slideshow__640x360/public/images/2302251_web1_SAR_NEW_050417_Sprinkler_01_web.jpg?itok=hZLciLu5kaZ-R-vR2VULGieiAUbbp82jdj0ecNkVRG93yMoDw_ChUqZRM73QrZSWgwpJzOLRZeUhkZFKcLsF1JGJtWak8-RVTDNGd2L89pSh7otTHh8tc10zanRGceSfVCfY3wzZwc2_KKpNpkYmqet1JWhuCUKq0wa2iir2vSPigQH0ZVnwS78rh2q4DsJIftxht7YGtCEgs5vP5N44GIW2d1EdxMehW0FDzyACdrU8ZU245RE2So-RWABpj_DUFH1A8rlZ8CZ9iBCCtZll42jci_cM4W4dkB2PyW4q_BZp6-sR4h6HmPwrtl8Qc4-9pAM7vmeRjK4iLN8gXxso3NOaFLC6BiV-aG0Yx87_fmmeAbAmT3S1Gv1YZuWhA_FLAmDF2vE5QLNtkGlO880lcIIKvjhUQo73hhfeTHUskZdt3kQ8kQ14f2ZCVsxH3aOqxDVZLSfTOkI1hE8U_NFu3GG8zX5TsUJ0QveIYXK8zgDafWIGSqUDqRjnLoy_fxdAaBwF7Nextl2svx_nfAeyPRSbt3GVDIriDJTw_ZI-P8xHmKE-y_TR8A4bl6lZkk1rtQtPGXUm1ZlftZuE26u1HN5-RoGr7z4v2ezeHVD_Xehex4vP5fgNpsEOoBVp=s0-l75-ft-l75-ft" alt="" /></a>

							<p><b>A smart watch that protects citizens from robbery</b><p>.<p>It could tell when you are scared, send your location to the nearest police station and to your next of kin and contains a kind of teaser</p>.

						</div>
					</section>

				<!-- Contact -->
					<section id="contact" class="four">
						<div class="container">

							

							
								 <div class="box1 details" style="text-align:center;"><h2 style="padding-bottom: 5px;font-size: 25px;">Add a Jido</h2>
								<form method="post" action="{% url 'plants:addplant' %}"><br>
								<div class="row">
									<div class="6u 12u$(mobile)" style="width:auto;margin-left:42px;"><input type="text" name="alias" placeholder="Give an Alias or use unique ID." /></div>
									
								<!--	<div class="12u$">
										<textarea name="message" placeholder="Message"></textarea>
									</div>-->
									<br><br><br>
									<div class="12u$" style="margin-top:40px;">
										<input type="submit" value="Add" style="background-color:#1e8c87"/>
									</div>
								</div>
							</form>
		   
		   
		   
		   </div>	
		

							

						</div>
					</section>

			</div>

		<!-- Footer -->
			<div id="footer">
				<hr style="clear:both;margin-bottom:3%; width:80%;border: 1.5px solid #988;">
				<!-- Copyright -->
					<ul class="copyright" style="text-align: center">
						<li><a href="#" target="blank">Jido-Tags</a></li>
					</ul>

			</div>

		<!-- Scripts -->
			<script src="{% static 'plants/js/jquery.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrollzer.min.js' %}"></script>
			<script src="{% static 'plants/js/skel.min.js' %}"></script>
			<script src="{% static 'plants/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'plants/js/main.js' %}"></script>

	</body>
</html>